datagrid:
    users-grid:
        extended_entity_name: %oro_user.entity.class%
        options:
            entityHint: user
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                    - u.createdAt
                    - u.updatedAt
                    - u.enabled
                from:
                    - { table: %oro_user.entity.class%, alias: u }
        columns:
            username:
                label: oro.user.grid.users.columns.username
            email:
                label: oro.user.grid.users.columns.email
            firstName:
                label: oro.user.grid.users.columns.firstName
            lastName:
                label: oro.user.grid.users.columns.lastName
            createdAt:
                label: oro.user.grid.users.columns.createdAt
                frontend_type: datetime
            updatedAt:
                label: oro.user.grid.users.columns.updatedAt
                frontend_type: datetime
            enabled:
                label: oro.user.grid.users.columns.enabled
                frontend_type: select
                choices:
                   - Inactive
                   - Active

        properties:
            id: ~
            update_link:
                type: url
                route: oro_user_update
                params:
                    - id
            view_link:
                type: url
                route: oro_user_view
                params:
                    - id
            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstName:
                    data_name: u.firstName
                lastName:
                    data_name: u.lastName
                createdAt:
                    data_name: u.createdAt
                updatedAt:
                    data_name: u.updatedAt
                enabled:
                    data_name: u.enabled
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                createdAt:
                    type: datetime
                    data_name: u.createdAt
                updatedAt:
                    type: datetime
                    data_name: u.updatedAt
                enabled:
                    type: choice
                    data_name: u.enabled
                    options:
                        field_options:
                            choices:
                               - Inactive
                               - Active

        actions:
            view:
                type:          navigate
                label:         View
                link:          view_link
                icon:          user
                acl_resource:  oro_user_user_view
                rowAction:     true
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  oro_user_user_update
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  oro_user_user_delete

    groups-grid:
        options:
            entityHint: group
        source:
            acl_resource: oro_user_group_view
            type: orm
            query:
                select:
                    - g.id
                    - g.name
                from:
                    - { table: OroUserBundle:Group, alias: g }
                where:
                    and:
                        - g.name <> '%oro_user.entity.class%::GROUP_DEFAULT'
        columns:
            name:
                label: oro.user.grid.groups.columns.name

        properties:
            id: ~
            update_link:
                type: url
                route: oro_user_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_group
                params:
                    - id

        actions:
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  oro_user_group_update
                rowAction:     true
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  oro_user_group_remove

        sorters:
            columns:
                name:
                    data_name: g.name
            default:
                name: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                name:
                    type: string
                    data_name: g.name

    roles-grid:
        options:
            entityHint: role
        source:
            acl_resource: oro_user_role_view
            type: orm
            query:
                select:
                    - r.id
                    - r.role
                    - r.label
                from:
                    - { table: OroUserBundle:Role, alias: r }
                where:
                    and:
                        - r.role <> '%oro_user.entity.class%::ROLE_ANONYMOUS'
        columns:
            label:
                label: oro.user.grid.roles.columns.label

        properties:
            id: ~
            update_link:
                type: url
                route: oro_user_role_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_role
                params:
                    - id

        actions:
            update:
                type:          navigate
                label:         Update
                link:          update_link
                icon:          edit
                acl_resource:  oro_user_role_update
                rowAction:     true
            delete:
                type:          delete
                label:         Delete
                link:          delete_link
                icon:          trash
                acl_resource:  oro_user_role_remove

        sorters:
            columns:
                label:
                    data_name: r.label
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                label:
                    type: string
                    data_name: r.label

    users-email-grid:
        extend: email-grid
        source:
            query:
                join:
                    inner:
                        folder:
                            join: e.folder
                            alias: f
                        origin:
                            join: f.origin
                            alias: o
                where:
                    and:
                        - o.id = :origin_id

    user-relation-grid:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                from:
                    - { table: OroUserBundle:User, alias: u }

        columns: []

        properties:
            id: ~

        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstName:
                    data_name: u.firstName
                lastName:
                    data_name: u.lastName
            default:
                id: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters: []

    role-users-grid:
        extend: user-relation-grid
        source:
            acl_resource: oro_user_role_update
            query:
                select:
                    - >
                      (CASE WHEN (:role_id IS NOT NULL) THEN
                        CASE WHEN (:role_id MEMBER OF u.roles OR u.id IN (:data_in)) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN u.id IN (:data_in) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as has_role
        columns:
            has_role:
                label: Has role
                editable: true
                frontend_type: boolean
            firstName:
                label: oro.user.grid.users.columns.firstName
            lastName:
                label: oro.user.grid.users.columns.lastName
            username:
                label: oro.user.grid.users.columns.username
            email:
                label: oro.user.grid.users.columns.email
        filters:
            columns:
                has_role:
                    type: boolean
                    data_name: has_role
                    filter_by_having: true
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
        sorters:
            multiple_sorting: true
            columns:
                has_role:
                    data_name: has_role

            default:
                has_role: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
                lastName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        options:
            requireJSModules:
              - oro/datagrid/column-form-listener
            columnListener:
                dataField: id
                columnName: has_role
                selectors:
                    included: '#roleAppendUsers'
                    excluded: '#roleRemoveUsers'

    group-users-grid:
        extend: user-relation-grid
        source:
            acl_resource: oro_user_group_update
            query:
                select:
                    - >
                      (CASE WHEN (:group_id IS NOT NULL) THEN
                        CASE WHEN (:group_id MEMBER OF u.groups OR u.id IN (:data_in)) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN u.id IN (:data_in) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as has_group
        columns:
            has_group:
                label: Has group
                editable: true
                frontend_type: boolean
            firstName:
                label: oro.user.grid.users.columns.firstName
            lastName:
                label: oro.user.grid.users.columns.lastName
            username:
                label: oro.user.grid.users.columns.username
            email:
                label: oro.user.grid.users.columns.email
        filters:
            columns:
                has_group:
                    type: boolean
                    data_name: has_group
                    filter_by_having: true
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstName:
                    type: string
                    data_name: u.firstName
                lastName:
                    type: string
                    data_name: u.lastName
        sorters:
            multiple_sorting: true
            columns:
                has_group:
                    data_name: has_group
            default:
                has_group: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
                lastName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        options:
            requireJSModules:
              - oro/datagrid/column-form-listener
            columnListener:
                dataField: id
                columnName: has_group
                selectors:
                    included: '#groupAppendUsers'
                    excluded: '#groupRemoveUsers'
