parameters:
    oro_user.manager.class:             Oro\Bundle\UserBundle\Entity\UserManager
    oro_user.status.manager.class:      Oro\Bundle\UserBundle\Entity\Manager\StatusManager
    oro_user.entity.class:              Oro\Bundle\UserBundle\Entity\User
    oro_user.group.entity.class:        Oro\Bundle\UserBundle\Entity\Group
    oro_user.role.entity.class:         Oro\Bundle\UserBundle\Entity\Role
    oro_user.security.provider.class:   Oro\Bundle\UserBundle\Security\UserProvider
    oro_user.security.login.class:      Oro\Bundle\UserBundle\EventListener\LoginSubscriber
    oro_user.user_menu.builder.class:   Oro\Bundle\UserBundle\Menu\UserMenuBuilder
    oro_user.role.listener.class:       Oro\Bundle\UserBundle\EventListener\RoleListener
    oro_user.role.manager.class:        Oro\Bundle\UserBundle\Entity\Manager\RoleManager
    oro_user.group.manager.class:       Oro\Bundle\UserBundle\Entity\Manager\GroupManager
    oro_user.entity_with_image.subscriber.class:            Oro\Bundle\UserBundle\Entity\EventListener\UploadedImageSubscriber
    oro_user.autocomplete.user.search_handler:              Oro\Bundle\UserBundle\Autocomplete\UserSearchHandler
    oro_user.email.owner.provider.class:                    Oro\Bundle\UserBundle\Entity\Provider\EmailOwnerProvider
    oro_user.change_password.subscriber.class:              Oro\Bundle\UserBundle\Form\EventListener\ChangePasswordSubscriber


services:
    oro_user.manager:
        class:                        %oro_user.manager.class%
        arguments:                    [%oro_user.entity.class%, "@doctrine.orm.entity_manager", "@security.encoder_factory"]

    oro_user.security.provider:
        class:                        %oro_user.security.provider.class%
        public:                       false
        arguments:                    ["@oro_user.manager"]

    oro_user.security.login:
        class:                        %oro_user.security.login.class%
        arguments:                    ["@oro_user.manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    oro_user.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ "oro_user.cache" ] ]

    oro_user.user_menu:
        class:                        %oro_user.user_menu.builder.class%
        arguments:
            - @security.context
        tags:
            - { name: oro_menu.builder, alias: usermenu }

    oro_user.role.listener:
        class:                        %oro_user.role.listener.class%
        arguments:                    ["@oro_security.link.sid_manager"]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    oro_user.status_manager:
        class:                        %oro_user.status.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager", "@oro_user.manager"]

    oro_user.role_manager:
        class:                        %oro_user.role.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_user.group_manager:
        class:                        %oro_user.group.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_user.entity_with_image.subscriber:
        class: %oro_user.entity_with_image.subscriber.class%
        arguments:
            - %kernel.root_dir%
        tags:
            - { name: doctrine.event_subscriber }

    # Autocomplete search handler
    oro_user.autocomplete.user.search_handler:
        class: %oro_user.autocomplete.user.search_handler%
        parent: oro_form.autocomplete.full_name.search_handler
        arguments:
            - @liip_imagine.cache.manager
            - %oro_user.entity.class%
            - ["username", "namePrefix", "firstName", "middleName", "lastName", "nameSuffix", "email"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: users, acl_resource: oro_user_user_view }

    oro_user.email.owner.provider:
        class: %oro_user.email.owner.provider.class%
        tags:
            - { name: oro_email.owner.provider, order: 1 }

    oro_user.change_password.subscriber:
        class: %oro_user.change_password.subscriber.class%
        arguments:
            - @form.factory
            - @security.context

    oro_user.event_listener.role_users_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - role_id
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.role-users-grid, method: onBuildAfter }

    oro_user.event_listener.group_users_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - group_id
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.group-users-grid, method: onBuildAfter }
