parameters:
    oro_form.autocomplete.security.class:  Oro\Bundle\FormBundle\Autocomplete\Security
    oro_form.autocomplete.search_registry.class: Oro\Bundle\FormBundle\Autocomplete\SearchRegistry
    oro_form.autocomplete.search_handler.class:  Oro\Bundle\FormBundle\Autocomplete\SearchHandler
    oro_form.autocomplete.full_name.search_handler.class:  Oro\Bundle\FormBundle\Autocomplete\FullNameSearchHandler

services:
    oro_form.autocomplete.security:
        class: %oro_form.autocomplete.security.class%
        arguments: [@oro_security.security_facade]

    oro_form.autocomplete.search_registry:
        class: %oro_form.autocomplete.search_registry.class%

    oro_form.autocomplete.search_handler:
        class: %oro_form.autocomplete.search_handler.class%
        abstract: true
        calls:
            # - [initSearchIndexer, ["@oro_search.index", %oro_search.entities_config%]]
            - [initDoctrinePropertiesByManagerRegistry, ["@doctrine"]]

    oro_form.autocomplete.full_name.search_handler:
        class: %oro_form.autocomplete.full_name.search_handler.class%
        abstract: true
        parent: oro_form.autocomplete.search_handler
        calls:
            - [ setNameFormatter, [@oro_locale.formatter.name] ]
