parameters:
    oro_organization.type.business_unit.class:                          Oro\Bundle\OrganizationBundle\Form\Type\BusinessUnitType
    oro_organization.handler.business_unit.class:                       Oro\Bundle\OrganizationBundle\Form\Handler\BusinessUnitHandler
    oro_organization.business_unit.form.type.business_unit.api.class:   Oro\Bundle\OrganizationBundle\Form\Type\BusinessUnitApiType
    oro_organization.business_unit.manager.api.class:                   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_organization.business_unit.entity.class:                        Oro\Bundle\OrganizationBundle\Entity\BusinessUnit
    oro_organization.business_unit.manager.class:                       Oro\Bundle\OrganizationBundle\Entity\Manager\BusinessUnitManager
    oro_organization.type.ownership_type.class:                         Oro\Bundle\OrganizationBundle\Form\Type\OwnershipType
    oro_organization.form.type.business_unit_tree_select_type.class:    Oro\Bundle\OrganizationBundle\Form\Type\BusinessUnitTreeSelectType
    oro_organization.form.extension.owner.class:                        Oro\Bundle\OrganizationBundle\Form\Extension\OwnerFormExtension
    oro_organization.form.transformer.business_unit_select.class:       Oro\Bundle\OrganizationBundle\Form\Transformer\BusinessUnitTransformer
    oro_organization.form.listener.class:                               Oro\Bundle\OrganizationBundle\Event\FormListener
    oro_organization.twig.get_owner.class:                              Oro\Bundle\OrganizationBundle\Twig\OwnerTypeExtension
    oro_organization.entity_ownership.listener.class:                   Oro\Bundle\OrganizationBundle\Event\RecordOwnerDataListener
    oro_organization.business_unit.listener.class:                      Oro\Bundle\OrganizationBundle\Event\BusinessUnitListener
    oro_organization.twig.business_units.class:                         Oro\Bundle\OrganizationBundle\Twig\BusinessUnitExtension
    oro_organization.provider.business_units.class:                     Oro\Bundle\OrganizationBundle\Provider\BusinessUnitGridService

services:
    oro_organization.form.business_unit:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["oro_business_unit_form", "oro_business_unit"]

    oro_organization.form.handler.business_unit:
        class:                        %oro_organization.handler.business_unit.class%
        scope:                        request
        arguments:                    ["@oro_organization.form.business_unit", "@request", "@doctrine.orm.entity_manager"]

    oro_organization.form.type.business_unit:
        class:                        %oro_organization.type.business_unit.class%
        tags:
            - { name: form.type, alias: oro_business_unit }

    # Business Unit API
    oro_organization.business_unit.manager.api:
        class: %oro_organization.business_unit.manager.api.class%
        arguments:
            - %oro_organization.business_unit.entity.class%
            - @doctrine.orm.entity_manager

    oro_organization.form.type.business_unit.api:
        class: %oro_organization.business_unit.form.type.business_unit.api.class%
        tags:
            - { name: form.type, alias: business_unit }

    oro_organization.form.business_unit.api:
        class:                        Symfony\Component\Form\Form
        factory_method:               createNamed
        factory_service:              form.factory
        arguments:                    ["business_unit", "business_unit", null]

    oro_organization.form.handler.api:
        class:                        %oro_organization.handler.business_unit.class%
        scope:                        request
        arguments:
            - @oro_organization.form.business_unit.api
            - @request
            - @doctrine.orm.entity_manager

    oro_organization.business_unit_manager:
        class:                        %oro_organization.business_unit.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_organization.form.type.ownership_type:
        class:                        %oro_organization.type.ownership_type.class%
        arguments:                    ["@translator"]
        tags:
            - { name: form.type, alias: oro_type_choice_ownership_type }

    oro_organization.method.get_ownership_type:
        tags:
            - { name: oro_service_method, service: oro_organization.form.type.ownership_type, method: getOwnershipsArray }

    oro_organization.form.type.business_unit_tree_select_type:
        class:                        %oro_organization.form.type.business_unit_tree_select_type.class%
        arguments:                    ["@oro_organization.form.transformer.business_unit_select"]
        tags:
            - { name: form.type, alias: oro_business_unit_tree_select }

    oro_organization.form.extension.owner:
        class:                        %oro_organization.form.extension.owner.class%
        arguments:
            - @security.context
            - @doctrine
            - @oro_security.owner.ownership_metadata_provider
            - @oro_organization.business_unit_manager
            - @oro_security.security_facade
            - @translator
        tags:
            - { name: form.type_extension, alias: form }

    oro_organization.form.transformer.business_unit_select:
        class: %oro_organization.form.transformer.business_unit_select.class%
        arguments: [@oro_organization.business_unit_manager]

    oro_organization.form.listener:
        class: %oro_organization.form.listener.class%
        tags:
            - { name: kernel.event_listener, event: entity_form.render.before, method: addOwnerField }

    oro_organization.twig.get_owner:
        class: %oro_organization.twig.get_owner.class%
        arguments:
            - @oro_entity_config.provider.ownership
        tags:
            - { name: twig.extension }

    oro_organization.entity_ownership.listener:
        class:                        %oro_organization.entity_ownership.listener.class%
        arguments:                    ["@service_container", "@oro_entity_config.provider.ownership"]
        tags:
             - { name: doctrine.event_listener, event: prePersist }

    oro_organization.business_unit.listener:
        class:                        %oro_organization.business_unit.listener.class%
        tags:
            - { name: doctrine.event_listener, event: preRemove }

    oro_organization.twig.business_units:
        class: %oro_organization.twig.business_units.class%
        arguments:
            - @oro_organization.business_unit_manager
        tags:
            - { name: twig.extension }

    oro_organization.event_listener.bu_update_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - business_unit_id
          - @oro_datagrid.datagrid.request_params
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.bu-update-users-grid, method: onBuildAfter }

    oro_organization.event_listener.bu_view_grid_listener:
        class: %oro_datagrid.event_listener.base_orm_relation.class%
        arguments:
          - business_unit_id
          - @oro_datagrid.datagrid.request_params
          - false
        tags:
          - { name: kernel.event_listener, event: oro_datagrid.datgrid.build.after.bu-view-users-grid, method: onBuildAfter }

    oro_organization.provider.business_units_grid:
        class: %oro_organization.provider.business_units.class%
        arguments:
          - @doctrine.orm.entity_manager
