parameters:
    oro_workflow.configuration_pass.replace_property_path.class: Oro\Bundle\WorkflowBundle\Model\ConfigurationPass\ReplacePropertyPath

    oro_workflow.condition_assembler.class: Oro\Bundle\WorkflowBundle\Model\Condition\ConditionAssembler
    oro_workflow.action_assembler.class: Oro\Bundle\WorkflowBundle\Model\Action\ActionAssembler
    oro_workflow.attribute_assembler.class: Oro\Bundle\WorkflowBundle\Model\AttributeAssembler
    oro_workflow.step_assembler.class: Oro\Bundle\WorkflowBundle\Model\StepAssembler
    oro_workflow.transition_assembler.class: Oro\Bundle\WorkflowBundle\Model\TransitionAssembler
    oro_workflow.workflow_assembler.class: Oro\Bundle\WorkflowBundle\Model\WorkflowAssembler
    oro_workflow.form_options_assembler.class: Oro\Bundle\WorkflowBundle\Model\FormOptionsAssembler

services:
    oro_workflow.configuration_pass.replace_property_path:
        class: %oro_workflow.configuration_pass.replace_property_path.class%
        arguments:
            - "data"

    oro_workflow.condition_assembler:
        class: %oro_workflow.condition_assembler.class%
        arguments:
            - @oro_workflow.condition_factory
        calls:
            - [addConfigurationPass, [@oro_workflow.configuration_pass.replace_property_path]]

    oro_workflow.action_assembler:
        class: %oro_workflow.action_assembler.class%
        arguments:
            - @oro_workflow.action_factory
            - @oro_workflow.condition_factory
        calls:
            - [addConfigurationPass, [@oro_workflow.configuration_pass.replace_property_path]]

    oro_workflow.attribute_assembler:
        class: %oro_workflow.attribute_assembler.class%

    oro_workflow.step_assembler:
        class: %oro_workflow.step_assembler.class%
        arguments:
            - @oro_workflow.form_options_assembler
        calls:
            - [addConfigurationPass, [@oro_workflow.configuration_pass.replace_property_path]]

    oro_workflow.transition_assembler:
        class: %oro_workflow.transition_assembler.class%
        arguments:
            - @oro_workflow.form_options_assembler
            - @oro_workflow.condition_factory
            - @oro_workflow.action_factory

    oro_workflow.workflow_assembler:
        class: %oro_workflow.workflow_assembler.class%
        arguments:
            - @service_container
            - @oro_workflow.configuration.config.workflow_sole
            - @oro_workflow.attribute_assembler
            - @oro_workflow.step_assembler
            - @oro_workflow.transition_assembler

    oro_workflow.form_options_assembler:
        class: %oro_workflow.form_options_assembler.class%
        arguments:
            - @oro_workflow.action_factory
        calls:
            - [addConfigurationPass, [@oro_workflow.configuration_pass.replace_property_path]]
