config:
    shim:
        'jquery-ui':
            deps:
                - 'jquery'
        'jquery-ui-timepicker':
            deps:
                - 'jquery-ui'
        'jquery.mousewheel':
            deps:
                - 'jquery'
        'jquery.numeric':
            deps:
                - 'jquery'
        'jquery.uniform':
            deps:
                - 'jquery'
        'jquery.select2':
            deps:
                - 'jquery'
        'jquery.jstree':
            deps:
                - 'jquery'
        'jstree/jquery.cookie':
            deps:
                - 'jquery.jstree'
        'jstree/jquery.hotkeys':
            deps:
                - 'jquery.jstree'
        'bootstrap':
            deps:
                - 'jquery'
        'bootstrap-tooltip':
            deps:
                - 'bootstrap'
        'popover-extra-placements':
            deps:
                - 'bootstrap-tooltip'
        'underscore':
            exports: '_'
        'backbone':
            deps:
                - 'jquery'
                - 'underscore'
            exports: 'Backbone'
        'backbone/bootstrap-modal':
            deps:
                - 'jquery'
                - 'underscore'
                - 'backbone'
    map:
        '*':
            'jquery': 'oro/jquery-setup'
            'jquery-ui': 'oro/jquery-ui-datepicker-l10n'
            'jquery-ui-timepicker': 'oro/jquery-ui-timepicker-l10n'
        'oro/jquery-setup':
            'jquery': 'jquery'
        'oro/jquery-ui-datepicker-l10n':
            'jquery-ui': 'jquery-ui'
        'oro/jquery-ui-timepicker-l10n':
            'jquery-ui-timepicker': 'jquery-ui-timepicker'
    paths:
        'text': 'bundles/oroui/lib/text.js'
        'json': 'bundles/oroui/lib/json2.js'
        'base64': 'bundles/oroui/lib/base64.js'
        'jquery': 'bundles/oroui/lib/jquery-1.10.2.js'
        'jquery-ui': 'bundles/oroui/lib/jquery-ui.min.js'
        'jquery-ui-timepicker': 'bundles/oroui/lib/jquery-ui-timepicker-addon.js'
        'jquery.mousewheel': 'bundles/oroui/lib/jquery/jquery.mousewheel.min.js'
        'jquery.numeric': 'bundles/oroui/lib/jquery/jquery.numeric.js'
        'jquery.uniform': 'bundles/oroui/lib/jquery/jquery.uniform.min.js'
        'jquery.select2': 'bundles/oroui/lib/jquery/select2.js'
        'jquery.jstree': 'bundles/oroui/lib/jstree/jquery.jstree.js'
        'jstree/jquery.cookie': 'bundles/oroui/lib/jstree/jquery.cookie.js'
        'jstree/jquery.hotkeys': 'bundles/oroui/lib/jstree/jquery.hotkeys.js'
        'bootstrap': 'bundles/oroui/lib/bootstrap.min.js'
        'bootstrap-tooltip': 'bundles/oroui/lib/bootstrap/js/bootstrap-tooltip.js'
        'popover-extra-placements': 'bundles/oroui/lib/bootstrap/js/popover-extra-placements.js'
        'underscore': 'bundles/oroui/lib/underscore.js'
        'backbone': 'bundles/oroui/lib/backbone.js'
        'backbone/bootstrap-modal': 'bundles/oroui/lib/backbone.bootstrap-modal.js'
        'oro/app': 'bundles/oroui/js/app.js'
        'oro/error': 'bundles/oroui/js/error.js'
        'oro/init-layout': 'bundles/oroui/js/init-layout.js'
        'oro/jquery-setup': 'bundles/oroui/js/jquery-setup.js'
        'oro/jquery-ui-datepicker-l10n': 'bundles/oroui/js/jquery-ui-datepicker-l10n.js'
        'oro/jquery-ui-timepicker-l10n': 'bundles/oroui/js/jquery-ui-timepicker-l10n.js'
        'oro/layout': 'bundles/oroui/js/layout.js'
        'oro/mediator': 'bundles/oroui/js/mediator.js'
        'oro/messenger': 'bundles/oroui/js/messenger.js'
        'oro/modal': 'bundles/oroui/js/modal.js'
        'oro/delete-confirmation': 'bundles/oroui/js/delete-confirmation.js'
        'oro/tools': 'bundles/oroui/js/tools.js'
        'oro/widget-manager': 'bundles/oroui/js/widget-manager.js'
        'oro/abstract-widget': 'bundles/oroui/js/widget/abstract-widget.js'
        'oro/block-widget': 'bundles/oroui/js/widget/block-widget.js'
        'oro/buttons-widget': 'bundles/oroui/js/widget/buttons-widget.js'
