parameters:
    oro_datagrid.datasource.orm.class:       Oro\Bundle\DataGridBundle\Datasource\Orm\OrmDatasource

services:
    oro_datagrid.datasource.orm:
        class: %oro_datagrid.datasource.orm.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @oro_security.acl_helper
        tags:
            - { name: oro_datagrid.datasource, type: orm }
