parameters:
    oro_querydesigner.querydesigner.manager.class:          Oro\Bundle\QueryDesignerBundle\QueryDesigner\Manager
    oro_querydesigner.provider.resolver.class:              Oro\Bundle\QueryDesignerBundle\Provider\SystemAwareResolver
    oro_querydesigner.grid.extension.orm_datasource.class:  Oro\Bundle\QueryDesignerBundle\Grid\Extension\OrmDatasourceExtension

services:
    oro_querydesigner.querydesigner.manager:
        class: %oro_querydesigner.querydesigner.manager.class%
        arguments:
            - []
            - @oro_querydesigner.provider.resolver

    oro_querydesigner.provider.resolver:
        class: %oro_querydesigner.provider.resolver.class%
        arguments:
            - @service_container

    oro_querydesigner.grid.extension.orm_datasource:
        class: %oro_querydesigner.grid.extension.orm_datasource.class%
        arguments:
            - @oro_querydesigner.querydesigner.manager
        tags:
            - { name: oro_datagrid.extension }
