config:
    paths:
        'oro/grid/action-launcher': 'bundles/orogrid/js/datagrid/action-launcher.js'
        'oro/grid/abstract-action': 'bundles/orogrid/js/datagrid/action/abstract-action.js'
        'oro/grid/delete-action': 'bundles/orogrid/js/datagrid/action/delete-action.js'
        'oro/grid/ajax-action': 'bundles/orogrid/js/datagrid/action/ajax-action.js'
        'oro/grid/mass-action': 'bundles/orogrid/js/datagrid/action/mass-action.js'
        'oro/grid/model-action': 'bundles/orogrid/js/datagrid/action/model-action.js'
        'oro/grid/navigate-action': 'bundles/orogrid/js/datagrid/action/navigate-action.js'
        'oro/grid/refresh-collection-action': 'bundles/orogrid/js/datagrid/action/refresh-collection-action.js'
        'oro/grid/reset-collection-action': 'bundles/orogrid/js/datagrid/action/reset-collection-action.js'
        'oro/grid/actions-panel': 'bundles/orogrid/js/datagrid/actions-panel.js'
        'oro/grid/action-column': 'bundles/orogrid/js/datagrid/column/action-column.js'
        'oro/grid/body': 'bundles/orogrid/js/datagrid/body.js'
        'oro/grid/action-cell': 'bundles/orogrid/js/datagrid/cell/action-cell.js'
        'oro/grid/boolean-cell': 'bundles/orogrid/js/datagrid/cell/boolean-cell.js'
        'oro/grid/html-cell': 'bundles/orogrid/js/datagrid/cell/html-cell.js'
        'oro/grid/date-cell': 'bundles/orogrid/js/datagrid/cell/date-cell.js'
        'oro/grid/datetime-cell': 'bundles/orogrid/js/datagrid/cell/datetime-cell.js'
        'oro/grid/number-cell': 'bundles/orogrid/js/datagrid/cell/number-cell.js'
        'oro/grid/select-cell': 'bundles/orogrid/js/datagrid/cell/select-cell.js'
        'oro/grid/select-row-cell': 'bundles/orogrid/js/datagrid/cell/select-row-cell.js'
        'oro/grid/string-cell': 'bundles/orogrid/js/datagrid/cell/string-cell.js'
        'oro/grid/filter-list': 'bundles/orogrid/js/datagrid/filter-list.js'
        'oro/grid/cell-formatter': 'bundles/orogrid/js/datagrid/formatter/cell-formatter.js'
        'oro/grid/datetime-formatter': 'bundles/orogrid/js/datagrid/formatter/datetime-formatter.js'
        'oro/grid/number-formatter': 'bundles/orogrid/js/datagrid/formatter/number-formatter.js'
        'oro/grid/grid': 'bundles/orogrid/js/datagrid/grid.js'
        'oro/grid/header-cell': 'bundles/orogrid/js/datagrid/header-cell/header-cell.js'
        'oro/grid/select-all-header-cell': 'bundles/orogrid/js/datagrid/header-cell/select-all-header-cell.js'
        'oro/grid/header': 'bundles/orogrid/js/datagrid/header.js'
        'oro/grid/abstract-listener': 'bundles/orogrid/js/datagrid/listener/abstract-listener.js'
        'oro/grid/column-form-listener': 'bundles/orogrid/js/datagrid/listener/column-form-listener.js'
        'oro/grid/callback-listener': 'bundles/orogrid/js/datagrid/listener/callback-listener.js'
        'oro/grid/page-size': 'bundles/orogrid/js/datagrid/page-size.js'
        'oro/grid/grid-views/view': 'bundles/orogrid/js/datagrid/grid-views/view.js'
        'oro/grid/grid-views/model': 'bundles/orogrid/js/datagrid/grid-views/model.js'
        'oro/grid/grid-views/collection': 'bundles/orogrid/js/datagrid/grid-views/collection.js'
        'oro/grid/pagination-input': 'bundles/orogrid/js/datagrid/pagination-input.js'
        'oro/grid/pagination': 'bundles/orogrid/js/datagrid/pagination.js'
        'oro/grid/router': 'bundles/orogrid/js/datagrid/router.js'
        'oro/grid/row': 'bundles/orogrid/js/datagrid/row.js'
        'oro/grid/toolbar': 'bundles/orogrid/js/datagrid/toolbar.js'
        'oro/grid/registry': 'bundles/orogrid/js/registry.js'
