parameters:
    oro_entity.orm.entity_class_resolver.class: Oro\Bundle\EntityBundle\ORM\EntityClassResolver

services:
    oro_entity.orm.entity_class_resolver:
        class: %oro_entity.orm.entity_class_resolver.class%
        arguments:
            - @doctrine
