parameters:
    doctrine.orm.entity_manager.class:                         Oro\Bundle\EntityBundle\ORM\OroEntityManager

    oro_entity.orm.entity_class_resolver.class:                Oro\Bundle\EntityBundle\ORM\EntityClassResolver
    oro_entity.orm.query.filter_collection.class:              Oro\Bundle\EntityBundle\ORM\Query\FilterCollection

services:
    oro_entity.orm.entity_class_resolver:
        class: %oro_entity.orm.entity_class_resolver.class%
        arguments:
            - @doctrine

    oro_entity.orm.sql_filter_collection:
        class:             %oro_entity.orm.query.filter_collection.class%
        arguments:         ["@doctrine.orm.entity_manager"]
