parameters:
    oro_entity.listener.navigation_listener.class:                 Oro\Bundle\EntityBundle\EventListener\NavigationListener
    oro_entity.owner.entity_config_subscriber.class:               Oro\Bundle\EntityBundle\EventListener\EntityConfigSubscriber
    oro_entity.entity_provider.class:                              Oro\Bundle\EntityBundle\Provider\EntityProvider
    oro_entity.entity_field_provider.class:                        Oro\Bundle\EntityBundle\Provider\EntityFieldProvider

services:
    oro_entity.listener.navigation_listener:
        class: %oro_entity.listener.navigation_listener.class%
        arguments:
            - @oro_security.security_facade
            - @doctrine.orm.entity_manager
            - @oro_entity_config.provider.entity
        tags:
            - { name: kernel.event_listener, event: oro_menu.configure.application_menu, method: onNavigationConfigure }

    oro_entity.owner.entity_config_subscriber:
        class: %oro_entity.owner.entity_config_subscriber.class%
        tags:
            - { name: kernel.event_subscriber }

    oro_entity.entity_provider:
        class: %oro_entity.entity_provider.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @oro_entity.orm.entity_class_resolver

    oro_entity.entity_field_provider:
        class: %oro_entity.entity_field_provider.class%
        arguments:
            - @oro_entity_config.provider.entity
            - @oro_entity.orm.entity_class_resolver
            - @doctrine
            - @oro_entity.entity_provider
