datagrid:
    email-grid:
        source:
            acl_resource: oro_email_view
            type: orm
            query:
                select:
                    - e
                    - @oro_email.datagrid_query_factory->getFromEmailExpression()
                from:
                    - { table: OroEmailBundle:Email, alias: e }
                join:
                    inner:
                        from_email_address:
                            join: e.fromEmailAddress
                            alias: a

        columns:
            fromEmailAddress:
                type: twig
                label: oro.email.datagrid.email.from_name
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/from.html.twig
            subject:
                type: twig
                label: oro.email.datagrid.email.subject
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/subject.html.twig
            sentAt:
                label: oro.email.datagrid.email.sentAt
                frontend_type: datetime
            recipients:
                type: twig
                label: oro.email.datagrid.email.recipients
                frontend_type: html
                template: OroEmailBundle:Email:Datagrid/Property/recipients.html.twig
        properties:
            id: ~
        sorters:
            columns:
                subject: { data_name: e.subject }
                sentAt:  { data_name: e.sentAt }
            default: { sentAt: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC }

        filters:
            columns:
                fromEmailAddress: { type: string,   data_name: a.email }
                subject:          { type: string,   data_name: e.subject }
                sentAt:           { type: datetime, data_name: e.sentAt }
        options: { entityHint: email }
